### Variables
@baseUrl = http://localhost:1234/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc3MzU5ODM3MSwiZXhwIjoxNzczNTk5MjcxfQ.2geeB9NjDDi7-6I0FV-pZrVa7SgZI_awtw5iRlzO5nM
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc3MzQyOTQ5NiwiZXhwIjoxNzc0MDM0Mjk2fQ.OWW4qhcWr30eE9Yhd-b25hN-YPIEUEfqQrSUNfjtKKQ
###POST create new user
POST http://localhost:1234/api/register
Content-Type: application/json

{
    "email": "sara@test.com",
    "username": "Sara",
    "password": "123456"
}

###POST login
POST http://localhost:1234/api/login
Content-Type: application/json

{
    "email": "sara@test.com",
    "password": "123456"
}

###GET users 
GET http://localhost:1234/api/me
Authorization: Bearer {{accessToken}}

###POST refresh token
POST http://localhost:1234/api/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}
######################### PROJECTS ################################
###GET projects
GET http://localhost:1234/api/project
Authorization: Bearer {{accessToken}}

###GET project by id
GET http://localhost:1234/api/project/2
Authorization: Bearer {{accessToken}}

###POST create new Project
POST http://localhost:1234/api/project/create
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Project 4",
    "description": "This is the fourth project"
}

###PUT update project
PUT http://localhost:1234/api/project/update/4
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Project 4 Updated",
    "description": "This is the fourth project updated",
    "color": "#FF5733"
}

###DELETE delete project
DELETE http://localhost:1234/api/project/delete/1
Authorization: Bearer {{accessToken}}

######################### TASKS ################################
###GET tasks by project id
GET http://localhost:1234/api/project/4/tasks
Authorization: Bearer {{accessToken}}

###POST create new task
POST http://localhost:1234/api/project/6/task/create
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Implement Schema",
    "description": "Create the schema for users",
    "assigneeId": 1
}

###PUT update task
PUT http://localhost:1234/api/project/4/task/update/4
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "Task 4 Updated",
    "description": "Task project 4 updated no member",
    "status": "in_progress",
    "assigneeId": 2
}

###DELETE delete task
DELETE http://localhost:1234/api/project/4/task/delete/4
Authorization: Bearer {{accessToken}}

######################### MEMBERS ################################
###GET members by project id
GET http://localhost:1234/api/project/3/members
Authorization: Bearer {{accessToken}}

###POST add member to project
POST http://localhost:1234/api/project/3/member/add
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "userId": 2,
    "role": "admin"
}

###PUT update member role
PUT http://localhost:1234/api/project/3/member/update/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "role": "admin"
}

###DELETE remove member from project
DELETE http://localhost:1234/api/project/3/member/delete/1
Authorization: Bearer {{accessToken}}
