### Variables
@baseUrl = http://localhost:1234/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MjY2Nzg5MCwiZXhwIjoxNzcyNjY4NzkwfQ.vB7N-IY0JOcrqQc75LrYy-L4FbRXcjGPwGXV6PGpt5A
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3MjY2Nzg5MCwiZXhwIjoxNzczMjcyNjkwfQ.nr-TFuLJXW4d0DQWjhd4svHL76_z1z1ruu5bniMmEbg
###POST create new user
POST http://localhost:1234/api/register
Content-Type: application/json

{
    "email": "andres@test.com",
    "username": "Andres",
    "password": "123456"
}

###POST login
POST http://localhost:1234/api/login
Content-Type: application/json

{
    "email": "andres@test.com",
    "password": "123456"
}

###POST create new user2
POST http://localhost:1234/api/register
Content-Type: application/json

{
    "email": "sara@test.com",
    "username": "Sara",
    "password": "234567"
}



###POST login2
POST http://localhost:1234/api/login
Content-Type: application/json

{
    "email": "sara@test.com",
    "password": "234567"
}

###GET users 
GET http://localhost:1234/api/me
Authorization: Bearer {{accessToken}}

###POST refresh token
POST http://localhost:1234/api/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}
######################### PROJECTS ################################
###GET projects
GET http://localhost:1234/api/project
Authorization: Bearer {{accessToken}}

###GET project by id
GET http://localhost:1234/api/project/2
Authorization: Bearer {{accessToken}}

###POST create new Project
POST http://localhost:1234/api/project/create
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Project 2",
    "description": "This is the second project"
}

###PUT update project
PUT http://localhost:1234/api/project/update/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Project 1 Updated",
    "description": "This is the first project updated"
}

###DELETE delete project
DELETE http://localhost:1234/api/project/delete/1
Authorization: Bearer {{accessToken}}